apiVersion: batch/v1
kind: CronJob
metadata:
  name: http-echo-cronjob
  labels:
    managed-by-deployment: http-echo-deployment
  annotations:
    controller.example.com/managed-by-deployment: http-echo-deployment
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: http-echo
              image: hashicorp/http-echo:0.2.3
              args: ["-text", "cron run"]
          restartPolicy: OnFailure
