apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob
  labels:
    managed-by-deployment: nginx-deployment
  annotations:
    controller.example.com/managed-by-deployment: nginx-deployment
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nginx
              image: nginx:1.21
              args: ["/bin/sh", "-c", "echo hello; sleep 10"]
          restartPolicy: OnFailure
